language: java
jdk:
  - openjdk11

branches:
  only:
    - develop

# Travis CI 서버 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean assemble"

# CI 완료시 메일로 알림
notifications:
  email:
    recipients:
      - jongbell4@gmail.com