## spring profile
##spring:
##  profiles:
## local server profile
##    include: loc
## dev server profile
##    include: dev
server:
  port: 8081

spring:
  profiles:
    active: loc
    #active: dev

mybatis:
  type-aliases-package: com.changbi.admin.domain
  mapper-locations: classpath:mappers/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true




