## spring profile
##spring:
##  profiles:
## local server profile
##    include: loc
## dev server profile
##    include: dev
server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.67.142.151:3306/changbi?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Seoul
    username: dev
    password: whddhks12.

mybatis:
  type-aliases-package: com.changbi.admin.domain
  mapper-locations: classpath:mappers/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true


cloud:
  ncp:
    credentials:
      access-key: aixST8b7k6LrNXweHNyy
      secret-key: FCjrVLM8aNhk1st2SE4s1bh7oXMxJC9Nsj8H7L70

